### ISSUE TITLE
Invalid/questionable APRS messages

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-aprs-protocol#31]
Checking the `valid_messages` with the [python-ogn-client](http://github.com/glidernet/python-ogn-client) I discovered some messages that instantly crashes the parser.

Course and speed must be 7 bytes long, so change `0/001` to `000/001`
https://github.com/glidernet/ogn-aprs-protocol/blob/bed93e0e842797838e584af90cb0a41cf520e8a3/valid_messages/OGADSB_ADSB.txt#L23

What is the meaning of the `/` at the end of the line?
https://github.com/glidernet/ogn-aprs-protocol/blob/bed93e0e842797838e584af90cb0a41cf520e8a3/valid_messages/OGCAPT_Capturs.txt#L4

The third does not crash the parser, but the "via" field is empty. So we see a message from `MYC78FF44` to `OGNMYC` without any receiver. I doubt that it is possible
https://github.com/glidernet/ogn-aprs-protocol/blob/bed93e0e842797838e584af90cb0a41cf520e8a3/valid_messages/OGNMYC_OGNtracker.txt#L1

**Comment by snip** [comment]
> What is the meaning of the `/` at the end of the line?
> 
> [ogn-aprs-protocol/valid_messages/OGCAPT_Capturs.txt](https://github.com/glidernet/ogn-aprs-protocol/blob/bed93e0e842797838e584af90cb0a41cf520e8a3/valid_messages/OGCAPT_Capturs.txt#L4)
> 
> Line 4 in [bed93e0](/glidernet/ogn-aprs-protocol/commit/bed93e0e842797838e584af90cb0a41cf520e8a3)

It looks to be a tentative to not provide altitude, but the / is part of the altitude field:

<img width="748" alt="Image" src="https://github.com/user-attachments/assets/c69cc55d-4994-4ea7-9108-ad0e132f6574" />

So looks to be an error.

@acasadoalonso this is the protocol you generate from your tool or the one sent by the OGN receivers directly?

**Comment by Meisterschueler** [comment]
... and a missing file extension here (I suggest ".txt"):
https://github.com/glidernet/ogn-aprs-protocol/blob/bed93e0e842797838e584af90cb0a41cf520e8a3/valid_messages/OGADSL_Tracker_with_ADSL

**Comment by acasadoalonso** [comment]
Fixed the ADSL and the ADSB valid messages files

**Comment by Meisterschueler** [comment]
Hello @acasadoalonso,
 thank you for your quick action

- [X] the file "OGADSB_ADSB.txt" is now correct and passes the parser
- [ ] the file "OGCAPT_Capturs.txt" is still incorrect. Some lines do not have the altitude (this is okay!), but there is a `/` from the altitude marker `/A=` left (see below)

```
# The following beacons are example for the Capture APRS format
# source: https://github.com/glidernet/ogn-aprs-protocol
#
FLRDDEEF1>OGCAPT,qAS,CAPTURS:/062744h4845.03N/00230.46E'000/000/            <- HERE!!!
FLRDDEEF1>OGCAPT,qAS,CAPTURS:/064243h4839.64N/00236.78E'000/085/A=000410    <- OK
FLRDDEEF1>OGCAPT,qAS,CAPTURS:/064548h4838.87N/00234.03E'000/042/A=000377    <- OK
FLRDDEEF1>OGCAPT,qAS,CAPTURS:/064847h4837.95N/00234.36E'000/000/            <- AND HERE
FLRDDEEF1>OGCAPT,qAS,CAPTURS:/065144h4837.56N/00233.80E'000/000/            <- AND HERE
FLRDDEEF1>OGCAPT,qAS,CAPTURS:/065511h4837.63N/00233.79E'000/000/            <- AND HERE
FLRDDEEF1>OGCAPT,qAS,CAPTURS:/070016h4837.63N/00233.77E'000/001/A=000360    <- OK
FLRDDEEF1>OGCAPT,qAS,CAPTURS:/070153h4837.62N/00233.77E'000/001/A=000344    <- OK
```

I cannot reopen this ticket... could the maintainer please reopen until resolved?

**Comment by acasadoalonso** [comment]
IMHO an slash after the fixed part of the APRS message is OK and conformant
